{{- if .Values.firebase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speaky.fullname" . }}-firebase
  labels:
    {{- include "speaky.labels" . | nindent 4 }}
data:
  service-account.json: {{ .Values.firebase.serviceAccount | required "firebase.serviceAccount is required when Firebase is enabled" | b64enc }}
{{- end }}