{{- if and .Values.sms.enabled (eq .Values.sms.method "phone") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speaky.fullname" . }}-sms
  labels:
    {{- include "speaky.labels" . | nindent 4 }}
data:
  SMS_FIGENSOFT_USERNAME: {{ .Values.sms.figensoft.username | required "sms.figensoft.username is required" | b64enc }}
  SMS_FIGENSOFT_PASSWORD: {{ .Values.sms.figensoft.password | required "sms.figensoft.password is required" | b64enc }}
{{- end }}