{{- if .Values.email.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speaky.fullname" . }}-smtp
  labels:
    {{- include "speaky.labels" . | nindent 4 }}
data:
  {{- with .Values.email.username }}
  SPRING_MAIL_USERNAME: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.email.password }}
  SPRING_MAIL_PASSWORD: {{ . | b64enc }}
  {{- end }}
{{- end }}