{
 "title": "Barman",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(barman_up, instance)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(barman_up, server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Barman instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Barman errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(barman_up{instance=~\"$instance.*\"}) - sum(barman_up{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Number of servers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(barman_backups_total{instance=~\"$instance.*\"}) by (server)"
    }
   ]
  },
  {
   "title": "Total number of backups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(barman_backups_total{instance=~\"$instance.*\"})"
    }
   ]
  },
  { "title": "Server $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "server" },
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (check) (barman_up{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "Last backup age",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()- barman_last_backup{instance=~\"$instance.*\", server=\"$server\"}",
     "legendFormat": "$instance: {{ server }}"
    }
   ]
  },
  {
   "title": "First backup age",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - barman_first_backup{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Available backups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_backups_total{instance=~\"$instance.*\", server=\"$server\"} - barman_backups_failed{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - barman_last_backup{instance=~\"$instance.*\", server=\"$server\"}",
     "legendFormat": "$instance: {{ server }}"
    }
   ]
  },
  {
   "title": "Last backup copy time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_last_backup_copy_time{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_backups_failed{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Last backup size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "barman_backup_size{instance=~\"$instance.*\", server=\"$server\", number=\"1\"}",
     "legendFormat": "$instance: {{ server }} backup size"
    },
    {
     "expr": "barman_backup_wal_size{instance=~\"$instance.*\", server=\"$server\", number=\"1\"}",
     "legendFormat": "$instance: {{ server }} WAL size"
    }
   ]
  }
 ]
}