{
 "title": "CPU Quota",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "nodeRole",
    "label": "Node Role",
    "query": {
     "query": "label_values(kube_node_role, role)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_role{role=~\"$nodeRole\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Maintenance cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", node=~\"$node\"}) - max(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Requests Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Requests Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Maintenance CPU Requests Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) / (sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"}) - max(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "CPU Limits Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) / sum(kube_node_status_capacity{resource=\"cpu\", unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Quota Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (node) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (node)"
    },
    {},
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (node) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", node=~\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU Quota Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node)"
    },
    {
     "expr": "sort_desc(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node))"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, namespace, node)"
    }
   ]
  },
  {
   "title": "CPU Quota Namespace",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\"}) by (namespace)"
    }
   ]
  }
 ]
}