{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info, namespace)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=~\"$namespace\"}, application)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(nodejs_version_info{application=~\"$application\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node.js Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{application=~\"$application\", pod=~\"$pod\", namespace=~\"$namespace\"}) by (version)",
     "legendFormat": "Node {{version}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{application=~\"$application\",pod=~\"$pod\",namespace=~\"$namespace\"}[2m]) * 100",
     "legendFormat": "User CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{application=~\"$application\",pod=~\"$pod\",namespace=~\"$namespace\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Heap Total - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{application=~\"$application\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  }
 ]
}