{
 "title": "PGBouncer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "server",
    "query": {
     "query": "label_values(pgbouncer_up, server)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(pgbouncer_databases_pool_size{server=\"$server\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backend Connections by Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_databases_current_connections{database=~\"$database\", server=~\"$server\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Backend Connections Usage by Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_databases_current_connections{database=~\"$database\", server=~\"$server\"}) / sum by (database) (pgbouncer_databases_max_connections{database=~\"$database\", server=~\"$server\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Client Connections by Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_pools_client_active_connections{database=~\"$database\", server=~\"$server\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Free Client Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pgbouncer_free_clients{database=~\"$database\", server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Transactions by database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pgbouncer_stats_sql_transactions_pooled_total{database=~\"$database\", server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Queries by database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pgbouncer_stats_queries_pooled_total{database=~\"$database\", server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}