{
 "title": "Spring Boot / R2DBC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "name_space_variable", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "query": {
     "query": "label_values(r2dbc_pool_idle_connections{namespace=\"$name_space_variable\"}, application)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(r2dbc_pool_idle_connections{namespace=\"$name_space_variable\", application=\"$application\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "r2dbc_pool_idle_connections{namespace=\"$name_space_variable\", application=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "Idle Connection - {{pod}} "
    },
    {
     "expr": "r2dbc_pool_pending_connections{namespace=\"$name_space_variable\", application=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "Pending Connection - {{pod}} "
    },
    {
     "expr": "r2dbc_pool_acquired_connections{namespace=\"$name_space_variable\", application=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "Acquired Connection - {{pod}} "
    }
   ]
  },
  {
   "title": "Max Allocated Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "r2dbc_pool_max_allocated_connections{namespace=\"$name_space_variable\", application=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "Max Allocated Connection - {{pod}}"
    }
   ]
  },
  {
   "title": "Max Pending Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "r2dbc_pool_max_pending_connections{namespace=\"$name_space_variable\", application=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "Max Pending Connection - {{pod}}"
    }
   ]
  }
 ]
}