{
 "title": "Spring Boot Integrations",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "name_space_variable", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(integration_request_seconds_count{namespace=~\"name_space_variable\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Calls per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(integration_request_seconds_count{namespace=~\"$name_space_variable\", hostname=~\"$host\"}[$__rate_interval])) by (hostname, path)",
     "legendFormat": "{{hostname}}{{path}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname, path) (rate(integration_request_seconds_sum{namespace=~\"$name_space_variable\", hostname=~\"$host\"}[$__rate_interval])) / sum by (hostname, path) (rate(integration_request_seconds_count{namespace=~\"$name_space_variable\", hostname=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}}{{path}}"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (hostname, path, method, le) (rate(integration_request_seconds_bucket{namespace=~\"$name_space_variable\", hostname=~\"$host\"}[2m])))",
     "legendFormat": "{{method}} - {{hostname}}{{path}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname, path, status) (rate(integration_request_seconds_count{namespace=~\"$name_space_variable\", hostname=~\"$host\", outcome!=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "{{status}} - {{hostname}}{{path}}"
    }
   ]
  }
 ]
}