{
 "title": "Spring Boot HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "query": "label_values(http_server_requests_seconds_sum{namespace=\"$namespace\"}, application)"
   },
   {
    "name": "method",
    "query": "label_values(http_server_requests_seconds_sum{namespace=\"$namespace\"}, method)"
   },
   {
    "name": "uri",
    "query": "label_values(http_server_requests_seconds_sum{namespace=\"$namespace\", method=~\"$method\", application=~\"$application\", uri!~\"/system/.*\"}, uri)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput by endpoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (application, method, uri) (rate (http_server_requests_seconds_count{namespace=~\"$namespace\",application=~\"$application\", method=~\"$method\", uri=~\"$uri\", outcome!=\"UNKNOWN\", uri!~\"/system/.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}} - {{application}}"
    }
   ]
  },
  {
   "title": "Throughput by application",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (rate (http_server_requests_seconds_count{namespace=~\"$namespace\", application=~\"$application\", method=~\"$method\", uri=~\"$uri\", outcome!=\"UNKNOWN\", uri!~\"/system/.*\"}[1m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, application) (rate(http_server_requests_seconds_sum{namespace=~\"$namespace\", application=~\"$application\", method=~\"$method\", uri=~\"$uri\", uri!~\"/system/.*\", status!~\"5..\", outcome!=\"UNKNOWN\"}[1m])) / sum by (method, uri, application) (rate(http_server_requests_seconds_count{application=~\"$application\", method=~\"$method\", uri=~\"$uri\", uri!~\"/system/.*\", status!~\"5..\", outcome!=\"UNKNOWN\"}[1m]))",
     "legendFormat": "{{method}} {{uri}} - {{application}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, application) (rate(http_server_requests_seconds_count{namespace=~\"$namespace\", application=~\"$application\", method=~\"$method\", uri=~\"$uri\", status=~\"5..\", outcome!=\"UNKNOWN\"}[1m]))",
     "legendFormat": "{{method}} {{uri}} - {{application}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, application, status) (rate(http_server_requests_seconds_count{namespace=~\"$namespace\", application=~\"$application\", method=~\"$method\", uri=~\"$uri\", status=~\"4..\", outcome!=\"UNKNOWN\"}[1m]))",
     "legendFormat": "{{method}} {{uri}} {{status}} - {{application}}"
    }
   ]
  }
 ]
}