apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bitcoind.fullname" . }}-secret
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.metrics.enabled }}
  BITCOIN_RPC_USER: {{ .Values.rpc.user | b64enc | quote }}
  BITCOIN_RPC_PASSWORD: {{ .Values.rpc.password | b64enc | quote }}
{{- end }}
  bitcoin.conf: {{ tpl .Values.configuration . | b64enc | quote }}