apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "bitcoind.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      accessModes: [ {{ .Values.persistence.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.extraPodLabels }}
        {{ tpl (.Values.extraPodLabels | toYaml) . | nindent 8 }}
        {{- end }}
      annotations:
        sidecar.istio.io/inject: 'false'
        config/checksum: {{ tpl .Values.configuration . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{ .Values.command | toJson }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.env }}
          env:
            {{ .Values.env | toYaml | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: rpc
              containerPort: 8332
          volumeMounts:
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /conf
            - name: home
              mountPath: /home/bitcoin
          readinessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 10
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 10
        {{- if .Values.metrics.enabled }}
        - name: bitcoin-exporter
          image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          ports:
            - name: metrics
              containerPort: 9332
          env:
            - name: REFRESH_SECONDS
              value: '10'
            - name: SMARTFEE_BLOCKS
              value: ''
            - name: 'HASHPS_BLOCKS'
              value: ''
            - name: BITCOIN_RPC_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "bitcoind.fullname" . }}-secret
                  key: BITCOIN_RPC_USER
            - name: BITCOIN_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "bitcoind.fullname" . }}-secret
                  key: BITCOIN_RPC_PASSWORD
        {{- end }}
      volumes:
        - name: home
          emptyDir: {}
        - name: conf
          secret:
            secretName: {{ template "bitcoind.fullname" . }}-secret
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end -}}