apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldap-auth-proxy.fullname" . }}-nginx-config
  labels:
    {{- include "ldap-auth-proxy.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            proxy_pass http://localhost:8888;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header {{ .Values.groupHeader | quote }} {{ .Values.ldapAuthorizeGroups | join "," | quote }};
        }
    }