apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "ldap-auth-proxy.labels" . | nindent 4 }}
data:
  LDAP_SERVER: {{.Values.ldapServer | b64enc | quote }}
  LDAP_BASE: {{.Values.ldapBase | b64enc | quote }}
  LDAP_BIND_DN: {{.Values.ldapBindDn | b64enc | quote }}
  LDAP_BIND_PASSWORD: {{.Values.ldapBindPassword | b64enc | quote }}
  LDAP_USER_FILTER: {{.Values.ldapUserFilter | b64enc | quote }}
  LDAP_GROUP_FILTER: {{.Values.ldapGroupFilter | b64enc | quote }}
  GROUP_HEADER: {{.Values.groupHeader | b64enc | quote }}
  HEADERS_MAP: {{.Values.headersMap | b64enc | quote }}
  URL_PATH_AUTH: {{ .Values.urlAuthPath | b64enc | quote }}