apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
data:
  IP2LOCATION_TOKEN: {{ .Values.ip2location.token | required "ip2location.token is required" | b64enc }}
  DATABASE_ENDPOINT: {{ printf "%s:%s" (.Values.database.host | required "database.host is required") (.Values.database.port | required "database.port is required" | toString) | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | required "database.name is required" | b64enc }}
  {{- if .Values.database.user }}
  DATABASE_USER: {{ .Values.database.user | b64enc }}
  {{- end }}
  {{- if .Values.database.password }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
  {{- end }}
