apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paranoyak-ai.fullname" $ }}-config
  labels:
    {{- include "paranoyak-ai.labels" $ | nindent 4 }}
data:
  API_BASE_URL: {{ .Values.config.backend.url | required "config.backend.url is required" | quote }}
  FRONTEND_BASE_URL: {{ .Values.config.frontend.url | required "config.frontend.url is required" | quote }}
  # DeepSeek Configuration
  DEEPSEEK_URL: {{ $.Values.config.deepseek.url | required "config.deepseek.url is required" | quote }}
  DEEPSEEK_MODEL: {{ $.Values.config.deepseek.model | required "config.deepseek.model is required" | quote }}

  # Keycloak Configuration
  KEYCLOAK_URL: {{ .Values.config.keycloak.url | required "config.keycloak.url is required" | quote }}
  KEYCLOAK_REALM: {{ .Values.config.keycloak.realm | required "config.keycloak.realm is required" | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.config.keycloak.clientId | required "config.keycloak.clientId is required" | quote }}

  # Postgres Configuration
  DATABASE_NAME: {{ $.Values.config.postgres.database | required "config.postgres.database is required" | quote }}
  DATABASE_HOST: {{ $.Values.config.postgres.host | required "config.postgres.host is required" | quote }}
  DATABASE_PORT: {{ $.Values.config.postgres.port | required "config.postgres.port is required" | quote }}

  # Metabase Configuration
  METABASE_BASE_URL: {{ .Values.config.metabase.url | required "config.metabase.url is required" | quote }}
