apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paranoyak-ai.fullname" $ }}-secret
  labels:
    {{- include "paranoyak-ai.labels" $ | nindent 4 }}
data:
  {{- if .Values.config.deepseek.apiKey }}
  DEEPSEEK_API_KEY: {{ .Values.config.deepseek.apiKey | b64enc }}
  {{- end }}

  METABASE_EMBED_SECRET: {{ .Values.config.metabase.embedSecret | required "config.metabase.embedSecret is required" | b64enc }}

  {{- if .Values.config.postgres.user }}
  DATABASE_USER: {{ .Values.config.postgres.user | b64enc }}
  {{- end }}
  {{- if .Values.config.postgres.password }}
  DATABASE_PASSWORD: {{ .Values.config.postgres.password | b64enc }}
  {{- end }}