apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paranoyak-ai.fullname" $ }}-secret
  labels:
    {{- include "paranoyak-ai.labels" $ | nindent 4 }}
data:
  {{- if .Values.config.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.config.openai.apiKey | b64enc }}
  {{- end }}

  METABASE_EMBED_SECRET: {{ .Values.config.metabase.embedSecret | required "config.metabase.embedSecret is required" | b64enc }}

  {{- if .Values.config.postgres.user }}
  DATABASE_USER: {{ .Values.config.postgres.user | b64enc }}
  {{- end }}
  {{- if .Values.config.postgres.password }}
  DATABASE_PASSWORD: {{ .Values.config.postgres.password | b64enc }}
  {{- end }}

  {{- if .Values.config.smtp.username }}
  SPRING_MAIL_USERNAME: {{ .Values.config.smtp.username | b64enc }}
  {{- end }}
  {{- if .Values.config.smtp.password }}
  SPRING_MAIL_PASSWORD: {{ .Values.config.smtp.password | b64enc }}
  {{- end }}